# version: '3.12'
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devusr
      - DB_PASS=changeme
    depends_on:
      - db
  
  db:
    image: postgres:17-alpine
    volumes:
      - dev-db-data:/var/lib/postgressql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devusr
      - POSTGRES_PASSWORD=changeme 

volumes:
  dev-db-data: